trigger:
- main

pool:
  name: Default


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python todo.py
  displayName: 'Run todo.py'

- script: echo "Hello from Hanan's agent!"
  displayName: 'Run a test script'
  